# Generated by Django 3.2.6 on 2021-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.CharField(blank=True, max_length=60, null=True)),
                ('battle_number', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_king', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_king', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_1', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_2', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_3', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_4', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_1', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_2', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_3', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_4', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_outcome', models.CharField(blank=True, max_length=60, null=True)),
                ('battle_type', models.CharField(blank=True, max_length=60, null=True)),
                ('major_death', models.CharField(blank=True, max_length=60, null=True)),
                ('major_capture', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_size', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_size', models.CharField(blank=True, max_length=60, null=True)),
                ('attacker_commander', models.CharField(blank=True, max_length=60, null=True)),
                ('defender_commander', models.CharField(blank=True, max_length=60, null=True)),
                ('summer', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('note', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
